- name: Debugging Information of the Site cloning it
  debug:
    msg:
      - "Home directory: {{ hugo_home.stdout }}"
      - "Username: {{ hugo_username }}"
      - "Group: {{ hugo_group }}"
      - "Directory: {{ hugo_home.stdout }}/{{ item.name }}"
      - "Repository: {{ hugo_ip }}/{{ item.name }}.git"

- name: Create target directory for repository
  ansible.builtin.file:
    path: "{{ hugo_home.stdout }}/{{ item.name }}"
    state: directory
    owner: "{{ hugo_username }}"
    group: "{{ hugo_group }}"
    mode: '0750'

- name: Clone the repository under target directory
  git:
    repo: "{{ hugo_ip }}/{{ item.name }}.git"
    dest: "{{ hugo_home.stdout }}/{{ item.name }}"
    update: yes
    version: main 

- name: Ensure correct ownership of cloned repo
  ansible.builtin.file:
    path: "{{ hugo_home.stdout }}/{{ item.name }}"
    state: directory
    recurse: yes
    owner: "{{ hugo_username }}"
    group: "{{ hugo_group }}"
