---
- name: Install Docker on Debian
  hosts: raspberry
  become: true

  vars:
    keyrings_directory: "/etc/apt/keyrings"
    gpg_key_location: "{{ keyrings_directory }}/docker.asc"

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes
    
    - name: Install dependencies for Docker repository
      apt:
        name: 
          - curl
          - ca-certificates
        state: present

    - name: Create {{ keyrings_directory }} directory
      file:
        path: "{{ keyrings_directory }}"
        state: directory
        mode: "0755"
    
    - name: Download Docker GPG key
      get_url: 
        url: https://download.docker.com/linux/debian/gpg
        dest: "{{ gpg_key_location }}"
        mode: "0644"

    - name: Get system architecture
      command: dpkg --print-architecture
      register: arch_output
      changed_when: false

    - name: Get Debian codename
      command: bash -c "source /etc/os-release && echo $VERSION_CODENAME"
      register: codename_output
      changed_when: false

    - name: Add Docker repository
      copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: |
          deb [arch={{ arch_output.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ codename_output.stdout }} stable
        mode: "0644"

    - name: Update apt package index after adding Docker repo
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
