---
- name: Rename baseURL and execute setup for Hugo sites
  hosts: raspberry
  become: true

  vars:
    site_ip_port: "{{ ansible_host }}:{{ hugo_port }}"

  tasks:
    - name: Get home directory of {{ hugo_username }}
      command: "echo ~{{ hugo_username }}"
      register: hugo_home
      changed_when: false

    - name: Process each Hugo repo
      include_tasks: /home/iamyaash/ansible-hugo-local/tasks/build-site.yaml
      loop: "{{ repos }}"
      loop_control:
        loop_var: item
