---
- name: Host Hugo Pages Using Nginx
  hosts: raspberry
  become: true

  vars:
    nginx_port: 2425
    server_ip: "192.168.31.101"
    hugo_conf: "hugo.local"
    nginx_conf_path: "/etc/nginx/sites-available/{{ hugo_conf }}"
    nginx_symlink_path: "/etc/nginx/sites-enabled/{{ hugo_conf }}"

  tasks:
    - name: Create Nginx config for Hugo sites
      copy:
        dest: "{{ nginx_conf_path }}"
        content: |
          server {
              listen {{ nginx_port }};
              server_name {{ server_ip }};

              location /stashed {
                  alias /home/hugo-pages/stashed/public;
                  index index.html;
                  try_files $uri $uri/ /index.html;
              }

              location /fedora {
                  alias /home/hugo-pages/fedora/public;
                  index index.html;
                  try_files $uri $uri/ /index.html;
              }

              location /blog {
                  alias /home/hugo-pages/blog/public;
                  index index.html;
                  try_files $uri $uri/ /index.html;
              }

              location /spells {
                  alias /home/hugo-pages/spells/public;
                  index index.html;
                  try_files $uri $uri/ /index.html;
              }
          }

    - name: Create symlink to sites-enabled
      file:
        src: "{{ nginx_conf_path }}"
        dest: "{{ nginx_symlink_path }}"
        state: link
        force: true

    - name: Test Nginx configuration
      command: nginx -t
      changed_when: false

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted