---
- name: Clone GitHub Repository Into Hugo Home Directory
  hosts: raspberry
  become: true

  tasks:
    - name: Get home directory of {{ hugo_username }}
      command: "echo ~{{ hugo_username }}"
      register: hugo_home
      changed_when: false

    - debug:
        msg:
          - "Home directory: {{ hugo_home.stdout }}"
          - "Username: {{ hugo_username }}"
          - "Group: {{ hugo_group }}"
          - "Directory: {{ hugo_home.stdout }}/{{ name_dir_stashed }}"
          - "Repository: {{ repo_url_stashed }}"
    
    - name: Create target directory for repository
      ansible.builtin.file:
        path: "{{ hugo_home.stdout }}/{{ name_dir_stashed }}"
        state: directory
        owner: "{{ hugo_username }}"
        group: "{{ hugo_group }}"
        mode: '0750'

    - name: Clone the repository under target directory
      git:
        repo: "{{ repo_url_stashed }}"
        dest: "{{ hugo_home.stdout }}/{{ name_dir_stashed }}"
        update: yes
        version: main 

    - name: Ensure correct ownership of cloned repo
      ansible.builtin.file:
        path: "{{ hugo_home.stdout }}/{{ name_dir_stashed }}"
        state: directory
        recurse: yes
        owner: "{{ hugo_username }}"
        group: "{{ hugo_group }}"
