---
- name: Clone GitHub Repository Into Hugo Home Directory
  hosts: raspberry
  become: true

  vars:
    hugo_username: "hugo-pages"
    hugo_group: "www-data"
    name_dir: "fedora"
    repo_url: "https://github.com/iamyaash/fedora.git"

  tasks:
    - name: Get home directory of {{ hugo_username }}
      command: "echo ~{{ hugo_username }}"
      register: hugo_home
      changed_when: false

    - name: Create target directory for repository
      ansible.builtin.file:
        path: "{{ hugo_home.stdout }}/{{ name_dir }}"
        state: directory
        owner: "{{ hugo_username }}"
        group: "{{ hugo_group }}"
        mode: '0750'

    - name: Clone the repository under target directory
      git:
        repo: "{{ repo_url }}"
        dest: "{{ hugo_home.stdout }}/{{ name_dir }}"
        update: yes

    - name: Ensure correct ownership of cloned repo
      ansible.builtin.file:
        path: "{{ hugo_home.stdout }}/{{ name_dir }}"
        state: directory
        recurse: yes
        owner: "{{ hugo_username }}"
        group: "{{ hugo_group }}"
