# credential information
ansible_user: hugo-pages
ansible_host: 192.168.31.101
ansible_port: 22
ansible_ssh_private_key_file: ~/.ssh/id_ed25519

# repository information
repo_url_stashed: "https://github.com/iamyaash/stashed.git"
name_dir_stashed: "stashed"

# setup information
hugo_username: "hugo-pages"
hugo_group: "www-data"
nginx_conf_dir: /etc/nginx/sites-available
nginx_symlink_path: /etc/nginx/sites-enabled
hugo_port: 2424
hugo_config: "hugo.yaml"